#
# Module manifest for module 'cVHDtoVMConnector'
#
# Generated by: Monte Hazboun
#
# Generated on: 6/22/2016
#
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '13d4e1e8-3f7d-44cd-8bb0-1dcd309051d3'

# Author of this module
Author = 'Monte Hazboun'

# Company or vendor of this module
#CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2016 Monte Hazboun. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DSC module to Add VHDs to a VM'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '4.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(cVHDtoVMConnector.psm1)

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# HelpInfo URI of this module
# HelpInfoURI = ''

}